### ISSUE TITLE
.gitignore for node_modules?

### ISSUE THREAD

**Issue by erelsgl** [harthur/brain#25]
When I fork this repo, and do "npm install", the folder is filled with node_modules, and since there is no .gitignore, git tries to commit them...

From what I read, there are two options for handling node_modules in git projects:

A. Keep all the node_modules in the git repository, together with my project, or:

B. Don't keep any node_modules in the git repository, and have a ".gitignore" file that contains "node_modules".

However, here, there are no node_modules, but also no .gitignore file...

I am not an expert, so maybe it's my mistake.

**Comment by umerjamil16** [comment]
You can create your own .gitignore file and add the folders/file names you want to exclude from your git repositories in production.

**Comment by amarkantk14** [comment]
To create .gitignore file use touch command 

user-name$ touch .gitignore
then open .gitignore file and add /node_modules

.gitignore
/node_modules

it will work.

**Comment by DMW007** [comment]
Seems not to work with subfolders. I have the following directory structure:

```
<git-root>
-- server
---- node_modules
```
By simply adding `node_modules` to `.gitignore`, a lot of files in `server/node_modules` are marked as unstaged. Only excluding the hole path `server/node_modules/` works as expected.

**Comment by rrajvanshi1947** [comment]
In your root folder within the .gitignore file, you need to write *node_modules to ignore the node_modules folder under any sub folder.

**Comment by Macil** [comment]
@rrajvanshi1947 Just "node_modules" without a / at the start will do that too. (.gitignore ignores the listed files in any directory, unless they start with /, in which case the line is expected to be the relative path to a file.)

**Comment by dmoraroca** [comment]
> To create .gitignore file use touch command
> 
> user-name$ touch .gitignore
> then open .gitignore file and add /node_modules
> 
> .gitignore
> /node_modules
> 
> it will work.

For me, it worked

**Comment by buddhaface** [comment]
good luck pushing .gitignore when you have it ignored

**Comment by Mstarr85** [comment]
Thank you!

**Comment by MelanieRogoff** [comment]
I saw a great answer on StackOverflow by a fellow programmer (https://stackoverflow.com/users/2854041/andrew-schreiber). He wrote: `touch .gitignore && echo "node_modules/" >> .gitignore && git rm -r --cached node_modules ; git status
`
It works perfectly (I'm using an OS).

**Comment by AlongTheDeveloper** [comment]
hello

**Comment by DavidCortes13** [comment]
Cual debería ser el modo correcto de guardar node_modules en mi proyecto, ¿Dentro o fuera del .git ignore?
