### ISSUE TITLE
Write null breaks streaming conventions

### ISSUE THREAD

**Issue by miketheprogrammer** [harthur/brain#35]
Would be better to have something like write ahead log similar to databases.
Where there is a max amount of data events before training is started. If max is not reached in some time frame, then go ahead with training and begin queuing up more data while training. however lock the training while currently training.

At the end of each training session, trained values should be copied, and the run function should work on these copies. 

By removing the null we can 

``` javascript
socket.on('data', function (buffer) { brainstream.write(buffer); } 
```

And all will work. I may try to create a pull request.

**Comment by robertleeplummerjr** [comment]
Is this solved?

**Comment by miketheprogrammer** [comment]
I am not sure this is even relevant. Also I should have never said WAL, i meant just a simple buffer-stream. "null" is in fact a valid terminal character of streams, but i remember something about the streaming implementation was broken for me, though it was more than likely fixed.

I think ill close this issue since i didnt exactly describe a problem and cases.

**Comment by robertleeplummerjr** [comment]
ty @miketheprogrammer!
