### ISSUE TITLE
you spelled contrast wrong in readme

### ISSUE THREAD

**Issue by 1UnboundedSentience** [harthur/brain#74]
its "contrast", see:

 color constrast demo

**Comment by IonicaBizau** [comment]
@1UnboundedSentience Please check out the updated repo, since this repository is not yet maintained. I fixed this in https://github.com/harthur-org/brain/commit/f5467966e2408d8467bd354c2dc066b939c66e21.

**Comment by robertleeplummerjr** [comment]
@1UnboundedSentience ping.  Also, nice work @IonicaBizau!

**Comment by robertleeplummerjr** [comment]
Consider closing as it is addressed in the community maintained version?

**Comment by robertleeplummerjr** [comment]
ty for finding this!
